--- !<SKIN>
contentType: "SKIN"
firstIndex: "2018-12-26 02:38"
game: "Unreal Tournament"
name: "PrototypePrometheus"
author: "Unknown"
description: "None"
releaseDate: "2001-08"
attachments: []
originalFilename: "ptprometheus.zip"
hash: "a2f533f9da2e721859d2d7c4940e6de478485322"
fileSize: 583241
files:
- name: "SoldierSkins_PTPrometheus.utx"
  fileSize: 1069340
  hash: "d408fb88f01c971637842493a78156c8774662e2"
otherFiles: 2
dependencies: {}
downloads:
- url: "http://www.ut-files.com/index.php?dir=Skins/SkinsP/&file=ptprometheus.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament/Skins/P/ptprometheus.zip"
  main: true
  repack: false
  state: "OK"
- url: "http://uttexture.com/UT/Downloads/Skins/Misc/SkinsP/ptprometheus.zip"
  main: false
  repack: false
  state: "OK"
- url: "http://medor.no-ip.org/index.php?dir=Skins/&file=ptprometheus.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://files.vohzd.com/unrealarchive/Unreal%20Tournament/Skins/P/a/2/f533f9/ptprometheus.zip"
  main: false
  repack: false
  state: "OK"
- url: "http://ut-files.com/index.php?dir=Skins/SkinsP/&file=ptprometheus.zip"
  main: false
  repack: false
  state: "OK"
deleted: false
skins:
- "PrototypePrometheus"
faces: []
model: "Unknown"
teamSkins: true
