--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2022-12-25 18:25"
game: "Unreal Tournament 2004"
name: "Forces game to start after a configurable amount of time."
author: "Unknown"
description: ""
releaseDate: "2003-08"
attachments: []
originalFilename: "WaitLimit.7z"
hash: "dcfcbd97a67eb37c91b202ae925e4f2a0beb3110"
fileSize: 1588
files:
- name: "WaitLimit.u"
  fileSize: 3007
  hash: "f62cb80c073596610884cc53c9c70801e476f4f0"
otherFiles: 2
dependencies: {}
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Mutators/F/d/c/fcbd97/WaitLimit.7z"
  main: true
  repack: false
  state: "OK"
- url: "https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament%202004/Mutators/F/d/c/fcbd97/WaitLimit.7z"
  main: false
  repack: false
  state: "OK"
links: {}
deleted: false
mutators:
- name: "Forces game to start after a configurable amount of time."
  description: ""
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
