--- !<MAP>
contentType: "MAP"
firstIndex: "2018-10-19 23:31"
game: "Unreal Tournament"
name: "DM-Prometheus]"
author: "Chris\"MADCAP\"Sheridan"
description: "None"
releaseDate: "2008-06"
attachments:
- type: "IMAGE"
  name: "dm-prometheus_shot_60664ef8_1.png"
  url: "https://f002.backblazeb2.com/file/unreal-archive-images/Unreal%20Tournament/Maps/DeathMatch/P/6/0/664ef8/dm-prometheus_shot_60664ef8_1.png"
originalFilename: "dm-prometheus].zip"
hash: "60664ef8d4a251df032908f476a8c23346612439"
fileSize: 2437021
files:
- name: "DM-Prometheus].unr"
  fileSize: 2746333
  hash: "028cee84107f7f946d76af911a9244f2150f42b5"
- name: "a3text.utx"
  fileSize: 2432297
  hash: "70be497ae27c4d1c0bd5283c6c72c4ecee918aa3"
otherFiles: 0
dependencies:
  DM-Prometheus].unr:
  - status: "OK"
    name: "a3text"
downloads:
- url: "http://medor.no-ip.org/index.php?dir=Maps/DeathMatch&file=dm-prometheus%5D.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament/Maps/DeathMatch/P/6/0/664ef8/dm-prometheus%5D.zip"
  main: true
  repack: false
  state: "OK"
- url: "https://files.vohzd.com/unrealarchive/Unreal%20Tournament/Maps/DeathMatch/P/6/0/664ef8/dm-prometheus%255D.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament/Maps/DeathMatch/P/6/0/664ef8/dm-prometheus%255D.zip"
  main: false
  repack: false
  state: "OK"
deleted: false
gametype: "DeathMatch"
title: "Prometheus"
playerCount: "8-16"
themes:
  Tech: 0.1
  Industrial: 0.8
  Egyptian: 0.1
bots: true
