--- !<MAP>
contentType: "MAP"
firstIndex: "2018-10-16 19:31"
game: "Unreal Tournament"
name: "DM-PrometheusFinal"
author: "Chris Sheridan"
description: "None"
releaseDate: "2006-12"
attachments:
- type: "IMAGE"
  name: "DM-PrometheusFinal_shot_1.png"
  url: "https://f002.backblazeb2.com/file/unreal-archive-images/Unreal%20Tournament/Maps/DeathMatch/P/DM-PrometheusFinal_shot_1.png"
originalFilename: "dm-prometheusfinal.zip"
hash: "4807767f827231244ddbb7bd3c5e7e67e89d038b"
fileSize: 277616
files:
- name: "DM-PrometheusFinal.unr"
  fileSize: 1058106
  hash: "7c7d6a538301e64bef7d7e82e136defa45a16337"
otherFiles: 1
dependencies:
  DM-PrometheusFinal.unr:
  - status: "MISSING"
    name: "SGTech1"
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament/Maps/DeathMatch/P/dm-prometheusfinal.zip"
  main: true
  repack: false
  state: "OK"
- url: "http://www.ut-files.com/index.php?dir=Maps/DeathMatch/MapsP/&file=dm-prometheusfinal.zip"
  main: false
  repack: false
  state: "OK"
- url: "http://medor.no-ip.org/index.php?dir=Maps/DeathMatch&file=dm-prometheusfinal.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://files.vohzd.com/unrealarchive/Unreal%20Tournament/Maps/DeathMatch/P/4/8/07767f/dm-prometheusfinal.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament/Maps/DeathMatch/P/4/8/07767f/dm-prometheusfinal.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://unrealarchiveusa.blob.core.windows.net/files/Unreal%20Tournament/Maps/DeathMatch/P/4/8/07767f/dm-prometheusfinal.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://unrealarchivesgp.blob.core.windows.net/files/Unreal%20Tournament/Maps/DeathMatch/P/4/8/07767f/dm-prometheusfinal.zip"
  main: false
  repack: false
  state: "OK"
links: {}
deleted: false
gametype: "DeathMatch"
title: "PrometheusFinal"
playerCount: "2-12"
themes:
  Tech: 0.8
  Industrial: 0.2
bots: true
