--- !<MAP>
contentType: "MAP"
firstIndex: "2018-10-16 19:31"
lastIndex: "2018-10-16 19:31"
game: "Unreal Tournament"
name: "DM-Prometheus]"
author: "Chris\"MADCAP\"Sheridan"
description: "None"
releaseDate: "2000-05"
attachments:
- type: "IMAGE"
  name: "DM-Prometheus]_shot_1.png"
  url: "https://f002.backblazeb2.com/file/unreal-archive-images/Unreal Tournament/Maps/DeathMatch/P/DM-Prometheus]_shot_1.png"
originalFilename: "dm-prometheus].zip"
hash: "78f95cc43e9d4a046861a9341fd4b2911ed5f1b3"
fileSize: 2501358
files:
- name: "DM-Prometheus].unr"
  fileSize: 2927762
  hash: "f5e736878f76292162c037e3a8914a86c9de3015"
- name: "a3text.utx"
  fileSize: 2432297
  hash: "70be497ae27c4d1c0bd5283c6c72c4ecee918aa3"
otherFiles: 2
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal Tournament/Maps/DeathMatch/P/dm-prometheus].zip"
  main: true
  added: "2018-10-16"
  lastChecked: "2018-10-16"
  ok: true
  repack: false
  deleted: false
- url: "http://www.ut-files.com/index.php?dir=Maps/DeathMatch/MapsP/&file=dm-prometheus%5D.zip"
  main: false
  added: "2018-10-17"
  lastChecked: null
  ok: false
  repack: false
  deleted: false
- url: "http://medor.no-ip.org/index.php?dir=Maps/DeathMatch&file=dm-prometheus%5D-2.zip"
  main: false
  added: "2018-10-19"
  lastChecked: null
  ok: false
  repack: false
  deleted: false
- url: "http://uttexture.com/UT/Downloads/Maps/DeathMatch/MapsP/dm-prometheus%5d.zip"
  main: false
  added: "2018-11-01"
  lastChecked: null
  ok: false
  repack: false
  deleted: false
deleted: false
gametype: "DeathMatch"
title: "Prometheus"
playerCount: "8-16"
