--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2019-02-19 19:31"
variationOf: "d981c36283fdac62309bcb358109b1e19765947c"
game: "Unreal Tournament 2004"
name: "Custom Config - change settings for in-game play."
author: "Unknown"
description: ""
releaseDate: "2002-11"
attachments: []
originalFilename: "customconfig.zip"
hash: "4a12d9b8907485b260b24ee5deb0d20840f3e381"
fileSize: 8016
files:
- name: "CustomConfig.u"
  fileSize: 16214
  hash: "f2d1ca413a6a41ce9caefdc2c1eda87d1070a96d"
otherFiles: 4
dependencies: {}
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Mutators/C/customconfig.zip"
  main: true
  repack: false
  state: "OK"
- url: "https://files.vohzd.com/unrealarchive/Unreal%20Tournament%202004/Mutators/C/4/a/12d9b8/customconfig.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament%202004/Mutators/C/4/a/12d9b8/customconfig.zip"
  main: false
  repack: false
  state: "OK"
deleted: false
mutators:
- name: "Custom Config - change settings for in-game play."
  description: ""
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
