--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2022-12-25 18:08"
game: "Unreal Tournament 2004"
name: "RainbowShockRifle v3 - Config"
author: "Shaun Goeppinger aka Ini"
description: "RainbowRifle config mutator"
releaseDate: "2010-04"
attachments: []
originalFilename: "RainbowShockRiflev3.7z"
hash: "6d9dcc99621028c9a2a16623da3695adfa12b997"
fileSize: 2553471
files:
- name: "RainbowShockRiflev3.u"
  fileSize: 242991
  hash: "aa090409760aea1f301da693452c503d2fb33172"
- name: "RainbowShockRifleTexv3.utx"
  fileSize: 13776667
  hash: "6646aba30554cdf89e65ef40168213efd3d0a965"
otherFiles: 3
dependencies:
  RainbowShockRiflev3.u:
  - status: "OK"
    name: "RainbowShockRifleTexv3"
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Mutators/R/6/d/9dcc99/RainbowShockRiflev3.7z"
  main: true
  repack: false
  state: "OK"
links: {}
deleted: false
mutators:
- name: "RainbowShockRifle v3 - Config"
  description: "RainbowRifle config mutator"
weapons:
- name: "Black Shock Rifle"
  description: "The Black Shock Rifle!"
- name: "Blue Shock Rifle"
  description: "The Blue Shock Rifle!"
- name: "Cyan Shock Rifle"
  description: "The Cyan Shock Rifle!"
- name: "Green Shock Rifle"
  description: "The Green Shock Rifle!"
- name: "Orange Shock Rifle"
  description: "The Orange Shock Rifle!"
- name: "Pink Shock Rifle"
  description: "The Pink Shock Rifle!"
- name: "Purple Shock Rifle"
  description: "The Purple Shock Rifle!"
- name: "Rainbow Shock Rifle"
  description: "The Rainbow Shock Rifle!"
- name: "Random Shock Rifle"
  description: "The Random Shock Rifle!"
- name: "Red Shock Rifle"
  description: "The Red Shock Rifle!"
- name: "White Shock Rifle"
  description: "The White Shock Rifle!"
- name: "Yellow Shock Rifle"
  description: "The Yellow Shock Rifle!"
vehicles: []
hasConfigMenu: false
hasKeybinds: false
