--- !<MAP>
contentType: "MAP"
firstIndex: "2018-10-16 19:31"
variationOf: "60664ef8d4a251df032908f476a8c23346612439"
game: "Unreal Tournament"
name: "DM-Prometheus]"
author: "Chris\"MADCAP\"Sheridan"
description: "None"
releaseDate: "2000-05"
attachments:
- type: "IMAGE"
  name: "dm-prometheus_shot_78f95cc4_1.png"
  url: "https://f002.backblazeb2.com/file/unreal-archive-images/Unreal%20Tournament/Maps/DeathMatch/P/7/8/f95cc4/dm-prometheus_shot_78f95cc4_1.png"
originalFilename: "dm-prometheus].zip"
hash: "78f95cc43e9d4a046861a9341fd4b2911ed5f1b3"
fileSize: 2501358
files:
- name: "DM-Prometheus].unr"
  fileSize: 2927762
  hash: "f5e736878f76292162c037e3a8914a86c9de3015"
- name: "a3text.utx"
  fileSize: 2432297
  hash: "70be497ae27c4d1c0bd5283c6c72c4ecee918aa3"
otherFiles: 2
dependencies:
  DM-Prometheus].unr:
  - status: "OK"
    name: "a3text"
    providedBy: null
downloads:
- url: "http://www.ut-files.com/index.php?dir=Maps/DeathMatch/MapsP/&file=dm-prometheus%5D.zip"
  main: false
  repack: false
  state: "OK"
- url: "http://medor.no-ip.org/index.php?dir=Maps/DeathMatch&file=dm-prometheus%5D-2.zip"
  main: false
  repack: false
  state: "OK"
- url: "http://uttexture.com/UT/Downloads/Maps/DeathMatch/MapsP/dm-prometheus%5d.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament/Maps/DeathMatch/P/7/8/f95cc4/dm-prometheus%5D.zip"
  main: true
  repack: false
  state: "OK"
- url: "https://utarchive.s3.eu-central-1.wasabisys.com/Unreal%20Tournament/Maps/DeathMatch/P/7/8/f95cc4/dm-prometheus%255D.zip"
  main: false
  repack: false
  state: "OK"
deleted: false
gametype: "DeathMatch"
title: "Prometheus"
playerCount: "8-16"
themes:
  Tech: 0.2
  Industrial: 0.7
  Egyptian: 0.1
bots: true
