--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2023-02-06 15:37"
game: "Unreal Tournament 2004"
name: "WeaponStuff allows you to change and configure different properties of weapons."
author: "Unknown"
description: ""
releaseDate: "2004-03"
attachments: []
originalFilename: "WeaponStuff3.zip"
hash: "8d4cd82eb0a6bdbd26c374289f0548fa82587549"
fileSize: 35534
files:
- name: "WeaponStuff.u"
  fileSize: 116105
  hash: "565e20c64679e6e88378bd80b2ce5336105618f9"
otherFiles: 2
dependencies: {}
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Mutators/W/8/d/4cd82e/WeaponStuff3.zip"
  main: true
  repack: false
  state: "OK"
links: {}
deleted: false
mutators:
- name: "WeaponStuff allows you to change and configure different properties of weapons."
  description: ""
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
