--- !<MAP>
contentType: "MAP"
firstIndex: "2018-10-16 19:31"
variationOf: "60664ef8d4a251df032908f476a8c23346612439"
game: "Unreal Tournament"
name: "DM-Prometheus]"
author: "Chris\"MADCAP\"Sheridan"
description: "None"
releaseDate: "2000-04"
attachments:
- type: "IMAGE"
  name: "dm-prometheus_shot_b3212227_1.png"
  url: "https://f002.backblazeb2.com/file/unreal-archive-images/Unreal%20Tournament/Maps/DeathMatch/P/dm-prometheus_shot_b3212227_1.png"
originalFilename: "dm-prometheus.zip"
hash: "b3212227fdd9565dd62872578210d74776187349"
fileSize: 2463755
files:
- name: "DM-Prometheus].unr"
  fileSize: 2746333
  hash: "028cee84107f7f946d76af911a9244f2150f42b5"
- name: "a3text.utx"
  fileSize: 2432297
  hash: "70be497ae27c4d1c0bd5283c6c72c4ecee918aa3"
otherFiles: 1
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament/Maps/DeathMatch/P/dm-prometheus.zip"
  main: true
  repack: false
  state: "OK"
- url: "http://www.ut-files.com/index.php?dir=Maps/DeathMatch/MapsP/&file=dm-prometheus.zip"
  main: false
  repack: false
  state: "OK"
- url: "http://medor.no-ip.org/index.php?dir=Maps/DeathMatch&file=dm-prometheus.zip"
  main: false
  repack: false
  state: "OK"
- url: "http://uttexture.com/UT/Downloads/Maps/DeathMatch/MapsP/dm-prometheus.zip"
  main: false
  repack: false
  state: "OK"
deleted: false
gametype: "DeathMatch"
title: "Prometheus"
playerCount: "8-16"
