--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2022-11-28 02:35"
game: "Unreal Tournament 3"
name: "EliteMachines_XV    -= Configurable =-"
author: "Unknown"
description: "Caution: This Weapon/Mutator Pack may be overwhelming. However, It is\
  \ fully customizable enough to have the perfect balance of Power or timidness."
releaseDate: "2008-11"
attachments: []
originalFilename: "EliteMachines_X.zip"
hash: "f81ee3b51c18c4d1d2cdc9562a1f3a4f822e721f"
fileSize: 12287549
files:
- name: "EliteMachines_Content_XV.upk"
  fileSize: 16725024
  hash: "fe0a974531e1e1f7272124d0856343cb7205e60c"
- name: "EliteMachines_XV.u"
  fileSize: 748001
  hash: "016a07af34d03595fdf9a68356142f39c97f4d0c"
- name: "UI_Scenes_EliteMachines_XV.upk"
  fileSize: 2273178
  hash: "100357edbde489e31316ba86641d7c5012a312a0"
otherFiles: 3
dependencies:
  EliteMachines_XV.u:
  - status: "OK"
    name: "EliteMachines_Content_XV"
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%203/Mutators/E/f/8/1ee3b5/EliteMachines_X.zip"
  main: true
  repack: false
  state: "OK"
- url: "https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament%203/Mutators/E/f/8/1ee3b5/EliteMachines_X.zip"
  main: false
  repack: false
  state: "OK"
links: {}
deleted: false
mutators:
- name: "EliteMachines_XV    -= Configurable =-"
  description: "Caution: This Weapon/Mutator Pack may be overwhelming. However, It\
    \ is fully customizable enough to have the perfect balance of Power or timidness."
weapons:
- name: "Elite_Weapon_Do Not Replace"
  description: "SuperClass for several of the Elite Weapons in this pack. This weapon\
    \ is not used. What is it even doing here?/"
- name: "Elite Impact Hammer"
  description: "The modern capabilities of the Impact Hammer has just overcome 'Leaps'\
    \ and 'Bounds'."
- name: "Elite Enforcer"
  description: "Well the AXON have outdone themselves yet again. This new toy is sure\
    \ to bring CHAOS on the battlefield."
- name: "Elite Insta-Gib"
  description: "Purchased mostly by the Krall from the Black Legion, Not only is the\
    \ weapon light weight and battle hardened, But comes in 2 versions. One for snipers\
    \ with adjustable zoom and one for the Combo Killers."
- name: "Elite Stinger"
  description: "Developed by the Necris, The Black Legion favors this new beauty.\
    \ They are anxious to put the new ammo to use and test it on the battlefield."
- name: "Elite Tiger Rifle"
  description: "Another favored weapon by Team Ronin. With this Rifles quiet stealthyness\
    \ and camo casings, Bishop Pronounced this weapon to be light weight enough to\
    \ carry 2 at a time."
- name: "Elite R.L. BFG"
  description: "ThunderCrash has always favored the 'Rocket Launcher' and is always\
    \ under new development. While many productions have never made it to the field,\
    \ Malcolm was pleased with this dual equipable version."
- name: "Goliath Cannon"
  description: "Developed by Team Ronin, the Goliath Cannon brought the ultimate power\
    \ from the Goliath Tank to a mobile, yet heavy tool."
- name: "Elite Lucifer Gun"
  description: "While similar to the Link gun, Lucifer Gun orgin and capabilities\
    \ are unknown. They just started showing up on the black market receintly."
- name: "Elite Bio Rifle"
  description: "Iron Guard requested a unique style of Bio Rifle Ammo. They wanted\
    \ the hazardous waste projected to be encased into a single glass bullet. So,\
    \ They modified the trigger function to allow for a further projection by means\
    \ of air pressure. Bio Waste has the ability to damage you over time."
- name: "Trans_Elite"
  description: "!!! Bloodbath !!!"
- name: "Redeem M@chine"
  description: "In persuit of destroying the Necris, Laindri Robot Corporation were\
    \ complaining the standard Redeemer was 'Big' and 'Bulky. They requested a more\
    \ versitile and stealthy 'Sniper Style' Redeemer for mas destruction."
vehicles: []
hasConfigMenu: true
hasKeybinds: false
