--- !<MAP>
contentType: "MAP"
firstIndex: "2019-02-19 20:06"
game: "Unreal Tournament 2004"
name: "CTF-Prometheus"
author: "{RA}SKYFURNACE"
description: "Prometheus Moon: Military Outpost Zeta-Prom: Welcome to the \"Zeta-Prom\"\
  . This dark, frozen, and hazardous terrain is your CTF battleground. Flag bases\
  \ are loacted in the old outposts of Zeta Prom, charges up, de-thawed, and ready\
  \ to go!"
releaseDate: "2002-11"
attachments:
- type: "IMAGE"
  name: "CTF-Prometheus_shot_1.png"
  url: "https://f002.backblazeb2.com/file/unreal-archive-images/Unreal%20Tournament%202004/Maps/Capture%20The%20Flag/P/CTF-Prometheus_shot_1.png"
- type: "IMAGE"
  name: "CTF-Prometheus_shot_2.png"
  url: "https://f002.backblazeb2.com/file/unreal-archive-images/Unreal%20Tournament%202004/Maps/Capture%20The%20Flag/P/CTF-Prometheus_shot_2.png"
originalFilename: "ctf-prometheus.zip"
hash: "73d2f3ad4c398cb6dea7615aeff5a3739b00c084"
fileSize: 2557240
files:
- name: "CTF-Prometheus.ut2"
  fileSize: 7594541
  hash: "8a0b72182f13d88b32f2b452ce100ee67a8fdf46"
otherFiles: 1
dependencies: {}
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Maps/Capture%20The%20Flag/P/ctf-prometheus.zip"
  main: true
  repack: false
  state: "OK"
- url: "http://www.unrealplayground.com/forums/downloads.php?do=file&id=941"
  main: false
  repack: false
  state: "MISSING"
- url: "https://files.vohzd.com/unrealarchive/Unreal%20Tournament%202004/Maps/Capture%20The%20Flag/P/7/3/d2f3ad/ctf-prometheus.zip"
  main: false
  repack: false
  state: "OK"
- url: "https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament%202004/Maps/Capture%20The%20Flag/P/7/3/d2f3ad/ctf-prometheus.zip"
  main: false
  repack: false
  state: "OK"
deleted: false
gametype: "Capture The Flag"
title: "CTF-Prometheus"
playerCount: "10-16"
themes:
  Tech: 1.0
bots: true
