--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2022-12-25 18:26"
game: "Unreal Tournament 2004"
name: "Druid's Mutator Config"
author: "Druid"
description: "Assigns mutators for various game types."
releaseDate: "2004-10"
attachments: []
originalFilename: "Druids Mutator.7z"
hash: "af859e665471d5f98186a6c367db06705cb639b6"
fileSize: 1977
files:
- name: "DM.u"
  fileSize: 2735
  hash: "f7e0f30ed2adefe8e4d2372b7debded36f944b1b"
otherFiles: 3
dependencies: {}
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Mutators/D/a/f/859e66/Druids%20Mutator.7z"
  main: true
  repack: false
  state: "OK"
links: {}
deleted: false
mutators:
- name: "Druid's Mutator Config"
  description: "Assigns mutators for various game types."
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
