--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2022-12-25 18:25"
game: "Unreal Tournament 2004"
name: "Monster Damage Config v2"
author: "Iniquitous"
description: "Configure damage for those problematic monsters in the MonsterDamageConfig.ini\
  \ file"
releaseDate: "2009-04"
attachments: []
originalFilename: "MonsterDamageConfigv2.7z"
hash: "8443fb2222e84acf09a59dda55f7cf239471c5c2"
fileSize: 3607
files:
- name: "MonsterDamageConfigv2.u"
  fileSize: 4926
  hash: "b78ac45cd697edf370dc4f7775af95c390212bd3"
otherFiles: 3
dependencies: {}
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Mutators/M/8/4/43fb22/MonsterDamageConfigv2.7z"
  main: true
  repack: false
  state: "OK"
links: {}
deleted: false
mutators:
- name: "Monster Damage Config v2"
  description: "Configure damage for those problematic monsters in the MonsterDamageConfig.ini\
    \ file"
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
