--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2023-02-13 05:34"
game: "Unreal Tournament 3"
name: "EM_XX    -= Configurable =-"
author: "Unknown"
description: "Caution:"
releaseDate: "2009-12"
attachments: []
originalFilename: "UT3 Elite_XX.7z"
hash: "822c701e129764873d8ee77067dd1c5b1f9cb11b"
fileSize: 12095681
files:
- name: "EM_XX_Content.upk"
  fileSize: 19070844
  hash: "9450e849c43e6f4f2399c1c06be390ae12b9ac99"
- name: "EM_XX.u"
  fileSize: 1366973
  hash: "9bad77fc780e58f61bc5d311f96564591250738f"
- name: "UI_Scenes_EM_XX.upk"
  fileSize: 2576153
  hash: "5ae6e393e0f824e07eb314bd8f90d0cc7ff32bdd"
otherFiles: 3
dependencies:
  EM_XX.u:
  - status: "OK"
    name: "EM_XX_Content"
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%203/Mutators/E/8/2/2c701e/UT3%20Elite_XX.7z"
  main: true
  repack: false
  state: "OK"
links: {}
deleted: false
mutators:
- name: "EM_XX    -= Configurable =-"
  description: "Caution:"
weapons:
- name: "Elite_Bio_Rifle"
  description: "Iron Guard requested a unique style of Bio Rifle Ammo. They wanted\
    \ the hazardous waste projected to be encased into a single glass bullet. So,\
    \ They modified the trigger function to allow for a further projection by means\
    \ of air pressure. Bio Waste has the ability to damage you over time."
- name: "Elite_Enforcer"
  description: "Well the AXON have outdone themselves yet again. This new toy is sure\
    \ to bring CHAOS on the battlefield."
- name: "Elite_FlakCannon"
  description: ""
- name: "Elite Impact Hammer"
  description: "The modern capabilities of the Impact Hammer has just overcome 'Leaps'\
    \ and 'Bounds'."
- name: "Elite_Link"
  description: "While similar to the Link gun, Lucifer Gun orgin and capabilities\
    \ are unknown. They just started showing up on the black market receintly."
- name: "Elite_Rocket_Launcher"
  description: "ThunderCrash has always favored the 'Rocket Launcher' and is always\
    \ under new development. While many productions have never made it to the field,\
    \ Malcolm was pleased with this dual equipable version."
- name: "Elite_Shock"
  description: "Purchased mostly by the Krall from the Black Legion, Not only is the\
    \ weapon light weight and battle hardened, But comes in 2 versions. One for snipers\
    \ with adjustable zoom and one for the Combo Killers."
- name: "Elite_Sniper_Rifle"
  description: "Another favored weapon by Team Ronin. With this Rifles quiet stealthyness\
    \ and camo casings, Bishop Pronounced this weapon to be light weight enough to\
    \ carry 2 at a time."
- name: "Elite_Stinger"
  description: "Developed by the Necris, The Black Legion favors this new beauty.\
    \ They are anxious to put the new ammo to use and test it on the battlefield."
- name: "Goliath_Cannon"
  description: "Developed by Team Ronin, the Goliath Cannon brought the ultimate power\
    \ from the Goliath Tank to a mobile, yet heavy tool."
- name: "RedeemMachine"
  description: "In persuit of destroying the Necris, Laindri Robot Corporation were\
    \ complaining the standard Redeemer was 'Big' and 'Bulky. They requested a more\
    \ versitile and stealthy 'Sniper Style' Redeemer for mas destruction."
- name: "TransElite"
  description: "!!! Bloodbath !!!"
- name: "Elite_Weapon"
  description: ""
vehicles: []
hasConfigMenu: true
hasKeybinds: false
